#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap   5

bspc config focused_border_color "#78aad8"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

picom &

# set wallpaper
feh --bg-fill ~/wallpaper*

# launch polybar
~/.config/polybar/launch.sh

# systray
if [[ ! $(pidof stalonetray) ]]; then
	stalonetray &
    sleep 0.1
	xdo hide -N stalonetray
	touch "/tmp/syshide.lock"
fi

# nm systray icon
nm-applet
