#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1920x1080 --rate 100 --rotate normal --right-of eDP-1
    bspc monitor eDP-1 -d 0 1 2 3
    bspc monitor HDMI-1-0 -d 4 5 6 7 8 9 10 11
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --off
    bspc monitor eDP-1 -d 0 1 2 3 4 5 6 7 8 9 10 11
fi

bspc config border_width 1
bspc config window_gap   5

bspc config focused_border_color "#a7c080"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

picom &

# set wallpaper
feh --bg-fill ~/wallpaper.*

# launch polybar
~/.config/polybar/launch.sh
