#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          10

bspc config focused_border_color "#78aad8"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
feh --bg-fill ~/Pictures/Wallpapers/mountain.jpg # wallpaper
~/.config/polybar/launch.sh

# systray
if [[ ! $(pidof stalonetray) ]]; then
	stalonetray &
    sleep 0.1
	xdo hide -N stalonetray
	touch "/tmp/syshide.lock"
fi
