import = [
    "~/.config/alacritty/everforest.toml"
]

[colors]
    draw_bold_text_with_bright_colors = true

[env]
    TERM = "xterm-256color"

[font]
    size = 8

[font.bold]
    family = "JetBrains Mono Nerd Font"
    style = "Bold"

[font.bold_italic]
    family = "JetBrains Mono Nerd Font"
    style = "BoldItalic"

[font.italic]
    family = "JetBrains Mono Nerd Font"
    style = "MediumItalic"

[font.normal]
    family = "JetBrains Mono Nerd Font"
    style = "Medium"

[selection]
    save_to_clipboard = false

[window]
    opacity = 0.8
