add_newline = true

# Use custom format:
format="$directory$git_branch$character"

# Prompt symbols 
[character]
error_symbol = "[](#db4b4b)"

[directory]
format = "[]($style)[[ ](bg:#292E42 fg:#7aa2f7)$path](bg:#292E42 fg:#c0caf5)[ ]($style)"
style = "bg:#1a1b26b3 fg:#292E42"

[git_branch]
format = "[]($style)[[ ](bg:#292E42 fg:#db4b4b)$branch](bg:#292E42 fg:#c0caf5)[ ]($style)"
style = "bg:#1a1b26b3 fg:#292E42"
